 # 서버포트 번호
server:
  port: 80

 # 콘솔 ANSI 색상
spring:
  output:
   ansi:
    enabled: always

 # thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

# datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

# security
  security:
    user:
      name: user1   # 디폴트 security username
      password: 1234  # password

    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 262064747928-r3dn315unejoev63iorecp87tuiav1r3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 3234484933519913
            client-secret: f83ea807872c2d4efe83df8990292f2a
            scope:
              - email
              - public_profile

          naver:         # 네이버는 추가로 설정해 줘야 할 것들이 더 있다.
            client-id: iDOYXRSo0V9Yd64Eq10K
            client-secret: GsmWF9IiLD
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
 mapper-locations: classpath:mapper/**/*.xml

app:
  # 파일 업로드 경로
  upload:
    path: upload

  # 페이징 관련 세팅값
  pagination:
    write_pages: 10  # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10   # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?

  # OAuth2
  oauth2:

    password: 1234 # OAUth 로그인 기본패스워드?

    # kakao 로그인 관련 세팅값
    kakao:
      client-id: 77ba367cf20e7c21e7f23d3b531f3c59 # 앱 키
      redirect-uri: http://localhost:8080/oauth2/kakao/callback  # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token  # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me  # 사용자 profile 요청 URI
